### ISSUE TITLE
Custom fields in advert-search set to 50% field width do not display correctly

### ISSUE THREAD

**Issue by 14lisat** [simpliko/wpadverts#114] opened 2019-10-23 18:35 UTC
When setting up custom fields, if two are of type short text with field width of 50% then arranged next to each other in GUI, they do not display as on the same row in the table when displayed adverts list, the second field drops to the next row. With several of these, appearance is jumbled.

Can see demonstrated with fields displayed under advanced search on page using adverts list.

Work around is to make each item 100% but not a great experience when you want something like fields, "made before year" and, "made after year" that are better displayed next to one another. And, forces scrolling on small screens.

Assuming the actual, partial row width should be 50% less the buffer space between the two fields(?),

**Comment by marekWin** [comment] 2019-10-25 08:55
Hi,
thank you for reporting this, we will check this in next update. If you looking for some instant help with your current page, please reach us via support e-mail.

**Comment by gwin** [comment] 2019-11-05 10:42
Hi @14lisat ,
sorry for the delay, i was taking a vacation and did not have access to GitHub.

If you are still having a problem with Custom Fields, please send a support request via the contact form at https://wpadverts.com/contact/ and include your website URL in the message. Most likely the problem is that there is a conflict between CF CSS and the theme and it should be easy to fix with a CSS snippet but i would need site URL to tell what CSS code will fix it.

I am closing this thread as the issue is rather with the Custom Fields plugin and not with WPAdverts itself (this issue tracker is for WPAdverts core only) and for now it seems to be specific to a selected theme.

**Closed by gwin** 2019-11-05 10:42 UTC
